# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-18 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('nombre_abreviado', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
