# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cientifico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cientifico',
            name='nombre_abreviado',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
