# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cientifico', '0001_initial'),
        ('categoriaTaxonomica', '0001_initial'),
        ('coleccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.PositiveIntegerField()),
                ('lugar_duplicado', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen_especimen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriaTaxonomica.CategoriaTaxonomica')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleccion.Coleccion')),
                ('determinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico')),
            ],
        ),
    ]
