# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especimen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especimen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_especimen/'),
        ),
    ]
