# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cientifico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('colector_ppal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='cientifico.Cientifico')),
            ],
        ),
        migrations.CreateModel(
            name='Colectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleccion.Coleccion')),
                ('colector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico')),
            ],
        ),
        migrations.AddField(
            model_name='coleccion',
            name='colectores_secu',
            field=models.ManyToManyField(blank=True, null=True, through='coleccion.Colectores', to='cientifico.Cientifico'),
        ),
    ]
