# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cientifico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('colectores_secu', models.CharField(max_length=800)),
                ('colector_ppal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico')),
            ],
        ),
    ]
