# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
