# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cientifico', '0001_initial'),
        ('coleccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='colector_ppal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='cientifico.Cientifico'),
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='colectores_secu',
        ),
        migrations.AddField(
            model_name='colectores',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coleccion.Coleccion'),
        ),
        migrations.AddField(
            model_name='colectores',
            name='colector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='colectores_secu',
            field=models.ManyToManyField(blank=True, null=True, through='coleccion.Colectores', to='cientifico.Cientifico'),
        ),
    ]
