# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180501_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
