# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_identificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
