# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180511_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('director', 'Director'), ('investigador', 'Investigador'), ('curador', 'Curador'), ('monitor', 'Monitor')], default='monitor', max_length=12),
        ),
    ]
