# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cientifico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTaxonomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('epiteto_especifico', models.CharField(max_length=200)),
                ('fecha_det', models.CharField(max_length=10)),
                ('categoria_infraespecifica', models.CharField(max_length=200)),
                ('epiteto_infraespecifico', models.CharField(max_length=200)),
                ('autor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cientifico.Cientifico')),
                ('autor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico')),
            ],
        ),
    ]
