# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cientifico', '0001_initial'),
        ('categoriaTaxonomica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Determinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_det', models.DateField()),
                ('categoria_taxomica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriaTaxonomica.CategoriaTaxonomica')),
                ('determinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cientifico.Cientifico')),
            ],
        ),
    ]
