# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriaTaxonomica', '0002_determinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='determinador',
            name='categoria_taxomica',
        ),
        migrations.RemoveField(
            model_name='determinador',
            name='determinador',
        ),
        migrations.DeleteModel(
            name='Determinador',
        ),
    ]
